add support name for api key
terralist/terralist pull request #363
Opened 2024-12-05 20:47 UTC by sergeylanzman

2024-12-06 11:51 UTC, valentindeaconu commented on web/src/api/apiKeys.ts
> +  name: string,
The field label was added here for this exact use case, but I left it undone on the server side. It is implemented only on the client side. Can you, please, choose one of them (either remove the name and use the label, or remove the label and keep the name one)?

2024-12-06 11:54 UTC, valentindeaconu requested changes
Thank you for this! I was also working on something a bit more complex on a different branch, but I think your solution is cleaner and can be delivered faster, so I'm ok with merging it.

I think we will need to also update the E2E tests (apply the migration on existing databases and dump them again). Are you able to also fix them?

2024-12-06 12:01 UTC, sergeylanzman commented
Thanks, i dont find how i can running tests on local machine, so starting debug with github PR

2024-12-07 20:08 UTC, sergeylanzman commented
Done with unit tests and e2e

2024-12-09 07:37 UTC, valentindeaconu approved these changes
The changes look good to me. Thank you again for this contribution!

2024-12-09 07:38 UTC, merged